# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8828eb1c8d4b14940f906d61f3369bb2d0c9187808feab81ba527ea92a37db0c804d1a5cb1d069bb74c074a8c8fceb31f461ccf93df793e2949148374aaa983

test:
  secret_key_base: eff6b7b372d936cf5f01e437bac8363af594be12dee7c6a15004202bd3c848a516b9cf9e5a0bca537fc5713fc2fdd4b71c4dbf2011a0a7be01be98edb5c2de7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
